
stages:
 - test
 - build
 - package
 - deploy
before_script:
- npm install
test:
  image: weboaks/node-karma-protractor-chrome
  script:
  - npm test
build:
  stage: build
  image: node:latest
  only:
    - master
  script:
    - npm install -g @angular/cli@14.2.0
    - npm install
    - ng build tst-form
    - ng build 
  artifacts:
    paths:
      - dist/
    expire_in: 2 hours
  cache:
    paths:
      - node_modules/
